### ISSUE TITLE
[Canal Digitaal] I have a Add-on that supports Canal Digitaal, as well as other M7 Group brands

### ISSUE THREAD

**Issue by michaelarnauts** [dut-iptv/dut-iptv#101]
I'm the author of [plugin.video.tvvlaanderen](https://github.com/add-ons/plugin.video.tvvlaanderen), and have recently added support for other M7 Group providers so I could support HD Austria and Focus Sat Romania. All of these services use the same  backend (Solocoo). Canal Digitaal also uses this backend, so it should be compatible with my Add-on.

Since I don't have credentials for Canal Digitaal, I can't test this myself, but I'm quite sure that the Addon will work fine, or only needs a small change to work. Is it possible if you guys could take a look and give it a try? I would like to include this Add-on to the Kodi repository. TV Vlaanderen, HD Austria and Focus Sat are already included, so the code is accepted according to the Kodi guidelines.

I've uploaded ZIP's for Leia and Matrix here: https://github.com/add-ons/plugin.video.tvvlaanderen/pull/50#issuecomment-1019281673

I've named my add-on `plugin.video.canaldigitaal.nl` so I don't conflict with your add-on :)

**Comment by dut-iptv** [comment]
I don't have a subscription at this time. Don't know if any of the users following my GitHub do either.

If I remember correctly I based my Canal Digitaal code on another M7 addon and it worked without a hitch and as far as I know it has been since that time.

If you want to look at my specific code for Canal Digitaal you can look at https://github.com/dut-iptv/dut-iptv/blob/master/plugin.video.canaldigitaal/resources/lib/api.py and https://github.com/dut-iptv/dut-iptv/blob/master/plugin.video.canaldigitaal/resources/lib/util.py. These two files include basically all Canal Digitaal specific code.

**Comment by dut-iptv** [comment]
You might also be able to get a trial subscription to Canal Digitaal IPTV (Bomvol or Vol) for a week for 0,01 euro. Just put in a dutch address and pay using paypal or creditcard.
