### ISSUE TITLE
[T Mobile ][1.4.4+matrix.1] No EPG

### ISSUE THREAD

**Issue by powermarcel10** [dut-iptv/dut-iptv#103]
Hi!

Since the latest 1 of 2 versions, since you fixed the previous bug, no epg data is available anymore.. Do you have any idea?

Cheers,
Marcel

**Comment by dut-iptv** [comment]
My EPG updater probably has the same issue that was fixed in 1.4.4.

The incorrect SSL certificate still being used by T-Mobile is unusable on most platforms other than major browsers which ship with extra certificates. This is not how SSL is supposed to work though.

Will see for a workaround for my EPG updater but could be a few days.

In the meantime please send a complaint to T-Mobile notifying them of their incorrect SSL certificate for t-mobiletv.nl

**Comment by dut-iptv** [comment]
Should be fixed.
Might be necessary to wait up to 12 hours or clean your cache
