### ISSUE TITLE
Ziggo Go + KPN playback issues

### ISSUE THREAD

**Issue by illuvattarr** [dut-iptv/dut-iptv#121]
Since a couple of weeks I'm experiencing issues with playback of Live TV on both Ziggo Go and KPN. Ziggo Go was working perfectly before, but KPN has been problematic for a longer period, resulting in me using Ziggo Go.

For Ziggo Go, I'm using the latest version and am logged in with my Ziggo account, but once I select a Live TV channel, it tries to load for about half a second and then returns to the channel list and nothing happens. I've tried re-adding the repo and reinstalling + resetting the addon, but still the same issue.

For KPN, I'm also using the latest version, and starting a Live TV channel does work, but it is constantly buffering, making it unwatchable. Nothing is wrong with my connection since I'm on high speed fiber and every other streaming app works without issue. I've also tried re-adding the repo and reinstalling + resetting the addon, but still the same issue.

Here is my kodi log: http://paste.osmc.tv/uzorejerus

The device I'm using is Vero 4k+ on Kodi 19

**Comment by dut-iptv** [comment]
Please follow the issue guidelines when creating an issue and create an issue per problem you have, debugging two problems in one does not work.

Start by trying the addons on a different platform (such as a Windows/Linux  laptop/desktop) to make sure the issue is not limited to your Vero 4K+ with OSMC.

**Comment by illuvattarr** [comment]
Thanks for answering. Sorry for combining it into one topic.
I just tried it on my Windows PC and both of the addons work fine, so it probably is some issue with Vero 4K+, which is weird since it was working a while ago.

**Comment by dut-iptv** [comment]
I assume you are running OSMC or LibreELEC?

There have been (and are currently) problems with Hardware decoding of H264 content on certain hardware platforms (mostly ARM) with these OSes.

Please note that my addons have no part in the handling of playback. They just show you which content is available, take care of authentication and present Kodi/Inputstream adaptive with information where and how to retrieve the stream manifest and (widevine) license. Playback is than taken care of by Kodi.

Unfortunately because of this I won't be able to help fix these issues as the problem and solution is not found in my addons.
