### ISSUE TITLE
BBC 1&2 missing in Canal Digitaal

### ISSUE THREAD

**Issue by Bubbelb** [dut-iptv/dut-iptv#5]
Well, a bit of a change in content. As I see it for the better.

The number of channels is fine now on Kodi. 76 channels in TV overview, so that is fixed. Thank you.
What I'm still missing is BBC 1 and BBC 2. There is a BBC First, BBC World and another, but BBC1 and BBC2 don't show up on the add-on.

For what I can see, everything else works like a charm.

**Comment by dut-iptv** [comment]
The channel list for Canaldigitaal is based on this list (when you are not logged in and click the X in the right top corner):
https://livetv.canaldigitaal.nl/livetv?channelType=available

BBC1 and BBC2 are not on this list.

However they show they are available the Canal Digitaal TV App on this list:
https://m7cdn.io/canaldigitaal/downloads/zenderlijst-tv-via-internet.pdf

There does not seem to be a machine parsable list of these channels though.

I would need to make a list of exceptions that are not in list 1 but are in list 2.

**Comment by Bubbelb** [comment]
Hmm, that's odd. There is a definitive difference in cht channel listing when you are logged-on, or not. Can I assist in creating (and maybe maintaining) the list manually? And if so, what is the format you prefer?

**Comment by dut-iptv** [comment]
I found 6 channels that might be streamable but are not automatically grabbed by my systems. 
I have created exceptions for these channels which should make them selectable in the addon.

Please check the channel selection -> Live TV screen tomorrow (because of 12 hours caching) or delete channels.json in the canaldigitaal userdata cache directory and check immediately (or Reset the addon).

The channels are:
Insight TV HD
BBC One HD (28)
BBC Two HD (28)
ZDF HD
ARD-Das Erste
arte HD

**Comment by Bubbelb** [comment]
All ok now.

I have reset the addons. I couldn't find the missing channels that quick, and I thought it never hurts to start clean again.
When I logged in again through the addon, I could find all the six cannels you mentioned.
So all fine now.
Thanks again.

**Comment by dut-iptv** [comment]
Np

Please feel free to create another issue if you come across any more missing channels.
