### ISSUE TITLE
[All] Add Movies filter to Replay TV, Make page size user changeable, Add option to use small images

### ISSUE THREAD

**Issue by alannl** [dut-iptv/dut-iptv#79]
Hi,
can you implement a listitem under "replay tv" which shows all movies that were broadcasted on tv and are available as vod?
Maybe it is better to remove the next page item and list all items on a single page.
Film1 movies don't show as vod in the epg while they are vod. Very cool that you have implemented this.
An option to make use of small size cover images.
thanks

**Comment by dut-iptv** [comment]
Will take this in consideration.

**Comment by dut-iptv** [comment]
Proper punctuation and title would help in deciphering your request(s) ;)

If I'm correct you request the following:

1. Add a list under ReplayTV which includes only movies 
 
**This has been added in 1.2.7 for all addons that support Replay TV
Proper listing is of course dependant on the TV providers supplying proper EPG categories**

2. Add an option to list all items on a single page instead of a maximum of 50 items per page

**This has been added in 1.2.7 for all addons
You can select the maximum amount of items on pages in the addon settings, pick a large number (like 99999) to list all items on the same page**

3. "Film1 movies don't show as vod in the epg while they are vod. Very cool that you have implemented this."

**Not sure if this is a question/request**

4. Add an option to make use of small size images

**This will be added to the wanted features list for possible addition on a later date**

Please note that 1.2.7. is not released yet, but will probably be released at the end of the day

**Comment by alannl** [comment]
Vriendelijk bedankt!

I have only one more request which I forgot to mention: sort by date for all VOD folders, based on when the video was added by the provider (latestOfferStartDate), so new content is easily spotted.

**Comment by alannl** [comment]
Ziggo go:
Movies that are broadcasted at a near future date are listed but show ~No Items ~.
Maybe it's better if these are shown in another folder with date of broadcast infp and excluded from the main list;
Or perhaps: add broadcast date to the listitem properties and add "sort by date" and an indicator in the listitem text that it isn't streamable yet.

**Comment by dut-iptv** [comment]
Movies that are broadcasted at a near future date will be correctly hidden in 1.2.8, this was already implemented in te past but bugged in some instances.

I will add sorting options requests to a separate issue for all addons as this is not Ziggo specific.

Closing
