### ISSUE TITLE
[NlZiet][Kodi 18][1.0.0] KeyError 'code' at line 137 in api_login

### ISSUE THREAD

**Issue by jbouwh** [dut-iptv/dut-iptv#8]
When starting a stream or retrying to login again an error occurs.
It seems the nlziet authentication redirect params have changed.

The error that occurs:

KeyError: 'code'
File "/resources/lib/api.py", line 137, in api_login
  auth_code = redirect_params['code'][0]

Version 1.0.0
Os: LibreElec 9.2.6 [Kodi 18.9.0 leila]
Hardware: Rpi 4B

**Comment by dut-iptv** [comment]
I was not able to reproduce your issue and was able to (re)login and play stream without issue.
Maybe a temporary issue at NLZiet?

**Comment by dut-iptv** [comment]
On analyzing the code I realize it might also be related to your refresh token being stale and it being necessary to do a full re-login.

Next version should handle this better.

**Comment by dut-iptv** [comment]
Try 1.0.3

**Comment by jbouwh** [comment]
Can you supply a version for leila. The matrix version has dependency issues with leila and won't install.

**Comment by jbouwh** [comment]
By the asy, I have done addon reset. This solves the issue for now. Logging out in logging in again was not enough.

**Comment by jbouwh** [comment]
Neverless I will try 1.0.3 when available

**Comment by dut-iptv** [comment]
Leia development was halted at 1.0.0

**Comment by jbouwh** [comment]
Ok, LibreElec stable still is at Leila, why not sync eos with a stable version of LibreElec/Kodi matrix?

**Comment by dut-iptv** [comment]
I felt like 1.0.0 was stable enough to leave it there for leia and focus my limited time on matrix which introduces some significant new options for my addons. Maintaining for leia and matrix is no small feat because of the step from Python 2 to Python 3.

As an exception and because you could consider this an addon breaking bug I have uploaded 1.0.1 for Leia NLZiet with the backported fix for this.
